"""หน้ากากของเดิม — เนื้อจริงย้ายไป `app/handlers/` แล้ว

ไฟล์นี้เคยเป็นไฟล์เดียว 1,133 บรรทัด ตอนนี้แยกเป็น 9 ไฟล์ตามหน้าที่
เก็บชื่อนี้ไว้เพื่อให้โค้ดและสคริปต์เทสต์เดิมที่ `import app.line_handler` ยังใช้ได้เหมือนเดิม

โค้ดใหม่ให้ import จาก `app.handlers` ตรงๆ — เริ่มอ่านที่ `app/handlers/router.py`
"""

from app.handlers import *  # noqa: F401,F403
from app.handlers import (  # noqa: F401
    _CANCEL_WORDS,
    _FRESH_COMMANDS,
    _LIST_QUESTION_WORDS,
    _PENDING_TTL_MIN,
    _PRIORITY_EMOJI,
    _PRIORITY_VALID,
    _ROUTINE_DAY_NAMES,
    _SUMMARY_WORDS,
    _THAI_TIME_WORDS,
    _TODAY_MONEY_WORDS,
    _YESTERDAY_MONEY_WORDS,
    _add_note,
    _add_routine,
    _add_task,
    _ai_deadline_to_utc,
    _cancel_recurring,
    _clear_pending,
    _delete_all,
    _delete_all_routines,
    _delete_expense_reply,
    _delete_routine,
    _delete_smart,
    _delete_task,
    _dispatch_ai,
    _done_all,
    _expense_quick_reply,
    _format_add_beautiful,
    _format_routine_days,
    _format_routine_line,
    _format_task_line,
    _get_pending,
    _get_routines_for_date,
    _get_tasks_for_date,
    _is_cancel,
    _label_for_date,
    _list_agenda_for_date,
    _list_all,
    _list_date,
    _list_message,
    _list_overdue,
    _list_routines,
    _list_this_week,
    _list_today,
    _list_tomorrow,
    _list_urgent,
    _local_date_or_none,
    _log_unknown,
    _looks_like_fresh_command,
    _looks_like_schedule_statement,
    _mark_done,
    _next_recurring_deadline,
    _recurring_label,
    _routine_matches_date,
    _routine_notify_str,
    _run_pipeline,
    _save_expense,
    _search_tasks,
    _set_pending,
    _set_priority,
    _snooze_task,
    _task_quick_reply,
    _try_expense_add,
    _try_expense_command,
    _try_strict,
    _update_routine,
    HELP_TEXT,
    NUMBERED,
    THAI_MONTHS,
    THAI_WEEKDAYS,
    handle_command,
)
